# Generated by Django 2.2.5 on 2019-10-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_time_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_posted']},
        ),
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.TextField(max_length=5000),
        ),
    ]
