# Generated by Django 2.2.5 on 2019-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191004_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='C:\\Users\\Sadek Irfan\\django\\practice_auth\\media\\image\\index.jpg', upload_to='image/'),
        ),
    ]
